### ISSUE TITLE
As a developer I want to understand whether I can block notifications in Android so that the app's 'Zones' can function

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Beeban-5-Rights#3]

**Comment by AccentSandeep** [comment]
After a lot of investigation on looking into blocking app notifications. This too seems possible.

In order to get this working, we will have to capture users preference to grant us permission to access Notification access. Once this permission is granted by the user the application then can decide which notifications can or can not be displayed. 

Capturing of user preference is just like an app requesting permission for accessing location services.

Requirements - User grants permission for 5 Rights app to access Notification access.
