### ISSUE TITLE
As a developer, I want to understand whether I can control mobile applications (allow/restrict) in Android so that the app's 'Zones' can function

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Beeban-5-Rights#7]

**Comment by AccentSandeep** [comment]
Blocking an app from another app on Android seems fairly possible.  In order to test this, developed a prototype app which does block other apps from launching.

Again, the solution to develop this functionality is the workaround one as there is no internal API provided by google to do this.  But the solution works and there are other apps published on google play store which does that and google doesn't penalise them.

**Comment by AccentSandeep** [comment]
The solution that was implemented  to block application doesn't work on recent Android releases. Google made many changes to API's from marshmallow onwards (API level 23+) and have restricted the usage of lot many api's like (getRunningProcessess etc)

Having said that, There is another way in which we could block applications on android using Accessibility settings. 

I have made use of accessibility settings and have tested it and it all works fine.

So Blocking applications is still possible.
